### ISSUE TITLE
Question about outbox ordering

### ISSUE THREAD

**Issue by WilcoKruijer** [evgeniy-khist/postgresql-event-sourcing#16]
Hi! First of all, awesome repo! Very interesting read. I'm trying to understand how to handle outboxes properly in Postgres, and this resource is very useful.

I have a question about your implementation, I'm wonder if you could clarify. In the "read new events" step, the outbox is queried after waiting for concurrent transactions to finish. I'm curious if the `ORDER BY e.TRANSACTION_ID ASC, e.ID ASC` clause is correct.

In the scenario below I'm working from your [reliable outbox diagram](https://github.com/eugene-khyst/postgresql-event-sourcing/raw/main/img/postgresql-reliable-outbox.svg).

Lets say after the first time reading events (and getting nothing) - but before the second time reading events, another transaction inserts some data. Then reading the data would give us the tuples `(851, 101), (852, 102), (853, 103)`. My thinking is that if we send this data in this order to our message broker, then our clients would receive this data in the wrong order. If some client integrates event 101, but not any further events, their aggregates would be in a state that never happened on the server. This is because event 102 actually committed first (thus updating aggregates). [^1]

This would be the full timeline
```
(begin) TX 851 - Seq 101
(begin) TX 852 - Seq 102

(end) TX 852
(end) TX 851

(begin) TX 853 - Seq 103
(end) TX 853

(wait for txs to finish)

SELECT tx_id, id FROM es_event 
  WHERE (tx_id, id) > (850, 100)
  ORDER BY tx_id ASC, id ASC
;
(return): (851, 101), (852, 102), (853, 103)
```

Would love to hear your thoughts!

[^1]: I realize the extra event (103) doesn't really add anything to the scenario, but it makes clear that we cannot integrate the events in reverse order either.

**Comment by eugene-khyst** [comment]
Hi @WilcoKruijer 
The sequence of events 101, 102, and 103 is ordered by the event creation time.
Event 101 started before the event 102 that's why it's ID is a smaller number.
In what order do you want the events to be sent to the message broker? Order events by the transaction commit time (event completion time): 102, 101, 103?

**Comment by WilcoKruijer** [comment]
Indeed, that sounds more "correct" to me.

Consider a scenario where events are adding/removing email addresses from some user/account aggregate. In our domain logic we want email addresses to be unique for users.

Our starting state of the world is 1 entry: abc@example.com

Lets say the transactions do this:
102 - Remove email "abc@example.com"
101 - Add email "abc@example.com"

In this screenshot the left hand side would be `(851, 101)` and right `(852, 102)`. Numbers indicate the order of things happening.
![image](https://github.com/user-attachments/assets/1709ec6b-7ec8-44f0-bf4e-a253df7450a0)

The global state of the world clearly went:
1. abc@example.com exists, 
3. nothing exists, 
3. abc@example.com exists.

Imagine some client that integrates events from our message broker. It already knows about the initial state of the world (abc@example.com exists). It then gets event 101 which says to add email abc@example.com. This is conflicting, since it already exists. We then get 102 which says to remove abc@example.com. In the state of the world on our client we end up with abc@example.com not existing, while on the server it actually does exist.

From this my conclusion would be that the only proper order would indeed be 102, 101, 103. And thus the query for reading events in this repo would be wrong. I don't really have an idea on how to fix it, however.

Do you agree with my assessment? Any idea on how you would fix this?

Thanks for replying so quickly as well!

**Comment by eugene-khyst** [comment]
The described situation is impossible thanks to optimistic concurrency control: https://github.com/eugene-khyst/postgresql-event-sourcing?tab=readme-ov-file#optimistic-concurrency-control

First, the aggregate version is updated and only after it, a new event is inserted. The `UPDATE` statement acquires lock on the row that will be released after the transaction commit.

```sql
UPDATE ES_AGGREGATE
   SET VERSION = :newVersion
 WHERE ID = :aggregateId
   AND VERSION = :expectedVersion
```

```sql
INSERT INTO ES_EVENT (TRANSACTION_ID, AGGREGATE_ID, VERSION, EVENT_TYPE, JSON_DATA)
VALUES(pg_current_xact_id(), :aggregateId, :version, :eventType, :jsonObj::json)
RETURNING ID, TRANSACTION_ID::text, EVENT_TYPE, JSON_DATA
```

Thus, if events 101 and 102 belong to the same aggregate, and event 101 started before 102, there is no way 102 will be committed before 101.

**Comment by WilcoKruijer** [comment]
Makes sense! Thanks again for your replies!
