### ISSUE TITLE
Postgres does not support subscribing on changes?

### ISSUE THREAD

**Issue by graforlock** [evgeniy-khist/postgresql-event-sourcing#3]
How about:

https://www.postgresql.org/docs/current/sql-notify.html

?

> When NOTIFY is used to signal the occurrence of changes to a particular table, a useful programming technique is to put the NOTIFY in a statement trigger that is triggered by table updates. In this way, notification happens automatically when the table is changed, and the application programmer cannot accidentally forget to do it.

**Comment by evgeniy-khist** [comment]
This issue is related to #2.
If PostgreSQL `LISTEN`/`NOTIFY` is applicable, then #2 will be automatically fixed.
Will investigate this.

**Comment by evgeniy-khist** [comment]
PostgreSQL `LISTEN`/`NOTIFY` functionality can be used as an alternative to the database polling but in practice the implementation is quite complex.
See the corresponding README section for more details: https://github.com/evgeniy-khist/postgresql-event-sourcing/tree/main#database-polling-alternatives

**Comment by evgeniy-khist** [comment]
PostgreSQL Listen/Notify functionality can be used as an alternative to the database polling.
See the corresponding README section for more details - https://github.com/evgeniy-khist/postgresql-event-sourcing#4-7-3
